const width = 125;
const height = 125;
setDocDimensions(width, height);
const a = bt.randIntInRange(1,11);
if (a==1){
  const happy = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(happy.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1h = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1h.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2h = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
  drawLines(eye2h.lines(),{fill:"black",stroke:"black",width:"5"})
  const mouth1h = new bt.Turtle()
    .setAngle((0, 269))
    .jump([16,55])
  .arc(180,47)
  drawLines(mouth1h.lines(),{fill:"white",stroke:"black",width:"5"})
  const mouth1 = new bt.Turtle()
  .jump([16, 49])
  .left(90)
  .forward(5)
  .right(90)
  .forward(93)
  .right(90)
  .forward(5)
  .right(90)
  .forward(93);
drawLines(mouth1.lines(),{fill:"white",stroke:"black",width:"10"})
}
else{
if(a==2){
 const mad = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(mad.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1m = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1m.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2m = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
  drawLines(eye2m.lines(),{fill:"black",stroke:"black",width:"5"})
  const mouth1h = new bt.Turtle()
    .setAngle((0, 90))
    .jump([103,23])
  .arc(180,40)
  drawLines(mouth1h.lines(),{fill:"white",stroke:"white",width:"5"})
   const mouth1h2 = new bt.Turtle()
    .setAngle((0, 90))
    .jump([103,26])
  .arc(180,40)
  drawLines(mouth1h2.lines(),{fill:"black",stroke:"black",width:"1"})
   const tounge = new bt.Turtle()
    .setAngle((0, -90))
    .jump([49,26])
  .arc(180,15)
  drawLines(tounge.lines(),{fill:"white",stroke:"black",width:"5"})
}
else{
if (a==3){
 const smily = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(smily.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1smile = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1smile.lines(),{fill:"black",stroke:"black",width:"5"})
  const smiley1 = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
  drawLines(smiley1.lines(),{fill:"black",stroke:"black",width:"5"})
  const smiley = new bt.Turtle()
    .setAngle((0, 272))
    .jump([16,55])
  .arc(180,47)
  drawLines(smiley.lines(),{fill:"white",stroke:"black",width:"10"})
}
else{
if (a==4){
  const sad = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(sad.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1s = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1s.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2s = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
  drawLines(eye2s.lines(),{fill:"black",stroke:"black",width:"5"})
  const mouth1s = new bt.Turtle()
    .setAngle((0, 91))
    .jump([101,24])
  .arc(180,39)
  drawLines(mouth1s.lines(),{fill:"white",stroke:"black",width:"10"})
}
else{
if(a==5){
   const mad = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(mad.lines(),{fill:"white",stroke:"black",width:"5"})
     const eyebrow1mad = new bt.Turtle()
    .setAngle((0, 120))
    .jump([100,95])
  .arc(180,11)
  drawLines(eyebrow1mad.lines(),{fill:"white",stroke:"black",width:"10"})
 const eyebrow2mad = new bt.Turtle()
    .setAngle((0, 60))
    .jump([46,83])
  .arc(180,11)
  drawLines(eyebrow2mad.lines(),{fill:"white",stroke:"black",width:"10"})
  const eye1mad = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1mad.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2mad = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
  drawLines(eye2mad.lines(),{fill:"black",stroke:"black",width:"5"})
 const mouth1mad = new bt.Turtle()
    .setAngle((0, 91))
    .jump([101,24])
  .arc(180,39)
  drawLines(mouth1mad.lines(),{fill:"white",stroke:"black",width:"10"})

}
else{
if(a==6){
   const cry = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(cry.lines(),{fill:"white",stroke:"black",width:"5"})
const eye1cry = new bt.Turtle()
  .setAngle((0, 90))
  .jump([50,77])
  .arc(180,14)
  drawLines(eye1cry.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2cry = new bt.Turtle()
  .setAngle((0, 90))
    .jump([104,77])
  .arc(180,14)
  drawLines(eye2cry.lines(),{fill:"black",stroke:"black",width:"5"})
 const tear = new bt.Turtle()
  .jump([26, 42])
  .left(90)
  .forward(34)
  .right(90)
  .forward(20)
  .right(90)
  .forward(20)
  .right(90);
drawLines(tear.lines(),{fill:"white",stroke:"black",width:"10"})
const tear2 = new bt.Turtle()
  .jump([80, 55])
  .left(90)
  .forward(20)
  .right(90)
  .forward(20)
  .right(90)
  .forward(39)
  .right(90);
drawLines(tear2.lines(),{fill:"white",stroke:"black",width:"10"})
  const mouth1cry = new bt.Turtle()
    .setAngle((0, 91))
    .jump([101,24])
  .arc(180,39)
  drawLines(mouth1cry.lines(),{fill:"white",stroke:"black",width:"10"})
  
}
else{
if(a==7){
  const happy = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(happy.lines(),{fill:"white",stroke:"black",width:"5"})
    const sunglasses = new bt.Turtle()
  .jump([22, 72])
  .left(90)
  .forward(25)
  .right(90)
  .forward(80)
  .right(90)
  .forward(25)
  .right(90);
drawLines(sunglasses.lines(),{fill:"black",stroke:"black",width:"10"})
  const glass = new bt.Turtle()
    .setAngle((0, 90))
    .jump([68,71.7])
  .arc(180,7)
  drawLines(glass.lines(),{fill:"white",stroke:"white",width:"10"})
  const mouth1h = new bt.Turtle()
    .setAngle((0, 269))
    .jump([23,55])
  .arc(180,40)
  drawLines(mouth1h.lines(),{fill:"white",stroke:"black",width:"10"})
}
else{
if(a==8){
  const happy = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(happy.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1h = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1h.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2h = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
  drawLines(eye2h.lines(),{fill:"black",stroke:"black",width:"5"})
const meh = new bt.Turtle()
  .jump([22, 30])
  .left(90)
  .forward(25)
  .right(100)
  .forward(80)
  .right(90)
  .forward(25)
  .right(90);
drawLines(meh.lines(),{fill:"black",stroke:"black",width:"1"})
}
else{
if(a==9){
  const happy = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(happy.lines(),{fill:"white",stroke:"black",width:"5"})
  const akka_face = new bt.Turtle()
  .jump([22, 30])
  .left(90)
  .forward(25)
  .right(100)
  .forward(80)
  .right(90)
  .forward(25)
  .right(90);
drawLines(akka_face.lines(),{fill:"black",stroke:"black",width:"1"})
  const akka_face1 = new bt.Turtle()
  .jump([22, 80])
  .left(90)
  .forward(10)
  .right(90)
  .forward(80)
  .right(90)
  .forward(10)
  .right(90);
drawLines(akka_face1.lines(),{fill:"black",stroke:"black",width:"1"})
  const akka_face2 = new bt.Turtle()
  .jump([58, 80.5])
  .left(90)
  .forward(20)
  .right(90)
  .forward(10)
  .right(90)
  .forward(39)
  .right(90);
drawLines(akka_face2.lines(),{fill:"white",stroke:"white",width:"5"})
}
else{
if(a==10){
   const mad = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(mad.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1m = new bt.Turtle()
  .jump([41,64])
  .arc(360,14)
  drawLines(eye1m.lines(),{fill:"black",stroke:"black",width:"5"})
  const eye2m = new bt.Turtle()
  .jump([84,80])
  .arc(360,8)
  drawLines(eye2m.lines(),{fill:"black",stroke:"black",width:"5"})
const mouth1h = new bt.Turtle()
    .setAngle((0, -60))
    .jump([25,30])
  .arc(180,40)
  drawLines(mouth1h.lines(),{fill:"white",stroke:"white",width:"5"})
   const mouth1h2 = new bt.Turtle()
    .setAngle((0, -60))
    .jump([29,25])
  .arc(180,40)
  drawLines(mouth1h2.lines(),{fill:"black",stroke:"black",width:"5"})
   const tounge = new bt.Turtle()
    .setAngle((0, -90))
    .jump([45,22])
  .arc(180,20)
  drawLines(tounge.lines(),{fill:"white",stroke:"black",width:"5"})
   }
else{
  const circle = new bt.Turtle()
const happy = new bt.Turtle()
  .jump([62.5,3.5])
  .arc(360,59)
  drawLines(happy.lines(),{fill:"white",stroke:"black",width:"5"})
    const eye1h = new bt.Turtle()
  .jump([41,68])
  .arc(360,14)
  drawLines(eye1h.lines(),{fill:"white",stroke:"black",width:"5"})
  const eye2h = new bt.Turtle()
  .jump([84,68])
  .arc(360,14)
drawLines(eye2h.lines(),{fill:"white",stroke:"black",width:"5"})
   const puipl1 = new bt.Turtle()
  .jump([41,85])
  .arc(360,5)
  drawLines(puipl1.lines(),{fill:"black",stroke:"black",width:"5"})
  const puipl2 = new bt.Turtle()
  .jump([84,85])
  .arc(360,5)
drawLines(puipl2.lines(),{fill:"black",stroke:"black",width:"5"})
  const akka_face = new bt.Turtle()
  .jump([22, 30])
  .left(90)
  .forward(20)
  .right(90)
  .forward(80)
  .right(90)
  .forward(20)
  .right(90);
drawLines(akka_face.lines(),{fill:"black",stroke:"black",width:"1"})
}}}}}}}}}}
// 330 lines of code hope you enjoy