name: Post Order Form on Merged PR

on:
  pull_request:
    types: [closed]

jobs:
  post-order-form:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - name: Post order form comment
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const number = context.payload.number;

            if (pr.merged && pr.labels.some(label => label.name === 'submission')) {
              const body = "🎉 Your PR has been merged! Go ahead and fill out the [order form](https://airtable.com/appv0BzBY2APyIXj6/shrhpWVXN5imMzUmw)!";

              await github.rest.issues.createComment({
                issue_number: number,
                owner: owner,
                repo: repo,
                body: body,
              });
            }
