name: Pull Request Previewer
run-name: Pull Request Previewer
on: 
    pull_request_target: 
        types: [opened,synchronize,reopened]
        paths: 'art/**' # The blot repo has art folder as compared to projects folder in onboard
jobs:
  comment-pr:
    runs-on: windows-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }} 
          script: | # As compared to the onboard repo, blot only requires index.js file whereas onboard requires gerber.zip, cart photo, schematics and pcb json files and a pdf file.
            const pr = context.payload.pull_request; 
            const owner = context.payload.repository.owner.login;
            const repo = context.payload.repository.name;
            const number = context.payload.number;
            const changedFiles = await github.request(`GET /repos/${owner}/${repo}/pulls/${number}/files`, {
              owner: owner,
              repo: repo,
              pull_number: number,
            });
            
            let commentbody = "<!-- BLOTPHEUS -->\n";
            let also = false;
            for (const file of changedFiles.data) {
              if (!file.filename.endsWith('index.js')) continue;
              const rawUrl = `https://raw.githubusercontent.com/${owner}/${repo}/${pr.head.sha}/${file.filename}`
              const blotUrl = `https://blot.hackclub.com/editor?src=${rawUrl}`;
              if (!also) {
                commentbody += `\`${file.filename}\` looks like art! [preview it in the editor](${blotUrl})\n`
                also = true
              } else {
                commentbody += `\`${file.filename}\` *also* looks like art! [preview it in the editor](${blotUrl})\n`
              }
            }
            if (!also) return;
            console.log(commentbody)
            const comments = await github.rest.issues.listComments({
              issue_number: number,
              owner: owner,
              repo: repo,
            });
            const ecomment = comments.data.find((c) => c.body.includes("BLOTPHEUS")); 
            if (ecomment) {
                github.rest.issues.updateComment({
                    comment_id: ecomment.id,
                    owner: owner,
                    repo: repo,
                    body: commentbody,
                });
            } else {
                github.rest.issues.createComment({
                  issue_number: number,
                  owner: owner,
                  repo: repo,
                  body: commentbody,
                });
            }
      
